In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
import csv

df = pd.read_csv('/content/marketing_campaign_dataset.csv', quoting=csv.QUOTE_NONE)

In [30]:
df.head(2)

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,"""$16","174.00""",6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01
2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,"""$11","566.00""",5.61,New York,German,116,7523,7,Fashionistas,2021-01-02

In [31]:
print('Duplicate Row:', df.duplicated().sum())

print('\nMissing values:')
print(df.isnull().sum())

print('\nData Types:')
print(df.dtypes)

# We check for the column names. Depending on quoting, they might have leading/trailing whitespaces or quotes.
print('\nAvailable Columns:', list(df.columns))

# Safely show samples if the columns exist
for col in ['Acquisition_Cost', 'Date', 'Campaign_ID']:
    if col in df.columns:
        print(f'\n{col} sample:')
        print(df[col].head(5))
    else:
        # Check if they exist with quotes or whitespaces
        matching_cols = [c for c in df.columns if col in c]
        if matching_cols:
            print(f'\nFound matching column name "{matching_cols[0]}" instead of "{col}":')
            print(df[matching_cols[0]].head(5))

print('\nTotal rows:', len(df))

Duplicate Row: 0

Missing values:
Campaign_ID         0
Company             0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Conversion_Rate     0
Acquisition_Cost    0
ROI                 0
Location            0
Language            0
Clicks              0
Impressions         0
Engagement_Score    0
Customer_Segment    0
Date                0
dtype: int64

Data Types:
Campaign_ID          object
Company              object
Campaign_Type        object
Target_Audience      object
Duration             object
Channel_Used        float64
Conversion_Rate      object
Acquisition_Cost     object
ROI                 float64
Location             object
Language             object
Clicks                int64
Impressions           int64
Engagement_Score      int64
Customer_Segment     object
Date                 object
dtype: object

Available Columns: ['Campaign_ID', 'Company', 'Campaign_Type', 'Target_Audience', 'Duration', 'Channel_Used', 'Conversion_Rate', 'Acquisition_Cost', 'ROI', 'Location', 'Language', 'Clicks', 'Impressions', 'Engagement_Score', 'Customer_Segment', 'Date']

Acquisition_Cost sample:
1    174.00"
2    566.00"
3    200.00"
4    724.00"
5    452.00"
Name: Acquisition_Cost, dtype: object

Date sample:
1    2021-01-01
2    2021-01-02
3    2021-01-03
4    2021-01-04
5    2021-01-05
Name: Date, dtype: object

Campaign_ID sample:
1    Innovate Industries
2         NexGen Systems
3      Alpha Innovations
4     DataTech Solutions
5         NexGen Systems
Name: Campaign_ID, dtype: object

Total rows: 200000

In [32]:
missing_rows = df[df.isnull().any(axis=1)]

print('Rows with missing values:', len(missing_rows))
display(missing_rows)

Rows with missing values: 0

Empty DataFrame
Columns: [Campaign_ID, Company, Campaign_Type, Target_Audience, Duration, Channel_Used, Conversion_Rate, Acquisition_Cost, ROI, Location, Language, Clicks, Impressions, Engagement_Score, Customer_Segment, Date]
Index: []

In [33]:
print("Dataset shape:", df.shape)

print("\nMissing values per column:")
print(df.isnull().sum())

print("\nTotal missing values:", df.isnull().sum().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Dataset shape: (200000, 16)

Missing values per column:
Campaign_ID         0
Company             0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Conversion_Rate     0
Acquisition_Cost    0
ROI                 0
Location            0
Language            0
Clicks              0
Impressions         0
Engagement_Score    0
Customer_Segment    0
Date                0
dtype: int64

Total missing values: 0

Duplicate rows: 0

In [34]:
print(df["Acquisition_Cost"].dtype)
print(df["Acquisition_Cost"].head())

print(df["Date"].dtype)
print(df["Date"].head())

print(df["Campaign_ID"].nunique())

object
1    174.00"
2    566.00"
3    200.00"
4    724.00"
5    452.00"
Name: Acquisition_Cost, dtype: object
object
1    2021-01-01
2    2021-01-02
3    2021-01-03
4    2021-01-04
5    2021-01-05
Name: Date, dtype: object
5

In [35]:
df_clean = df.copy()

df_clean['Acquisition_Cost'] = pd.to_numeric(df['Acquisition_Cost'].str.replace("$", "", regex=False).str.replace(",", "", regex=False),errors="coerce")
df_clean['Date'] = pd.to_datetime(df['Date'],format = "%d/%m/%Y", errors="coerce")


print(df_clean["Acquisition_Cost"].dtype)
print(df_clean["Date"].dtype)


print(df_clean[["Acquisition_Cost", "Date"]].isnull().sum())

display(df_clean.head())

float64
datetime64[ns]
Acquisition_Cost    200000
Date                200000
dtype: int64

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,"""$16",NaN,6.29,Chicago,Spanish,506,1922,6,Health & Wellness,NaT
2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,"""$11",NaN,5.61,New York,German,116,7523,7,Fashionistas,NaT
3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,"""$10",NaN,7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,NaT
4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,"""$12",NaN,5.55,Miami,Mandarin,217,1820,7,Health & Wellness,NaT
5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,"""$16",NaN,6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,NaT

In [36]:
print("Original date samples:")
print(df["Date"].head(10).tolist())

print(df["Date"].dtype)

print("\nDate examples from cleaned data:")
print(df_clean["Date"].head(10))

print("\nDate values that failed conversion:")
print(df.loc[df_clean["Date"].isna(), "Date"].head(10).tolist())

Original date samples:
['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08', '2021-01-09', '2021-01-10']
object

Date examples from cleaned data:
1    NaT
2    NaT
3    NaT
4    NaT
5    NaT
6    NaT
7    NaT
8    NaT
9    NaT
10   NaT
Name: Date, dtype: datetime64[ns]

Date values that failed conversion:
['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08', '2021-01-09', '2021-01-10']

In [37]:
# Convert dates using automatic format inference
df_clean["Date"] = pd.to_datetime(
    df["Date"].astype("string").str.strip(),
    errors="coerce"
)

# Verify
print("Date data type:", df_clean["Date"].dtype)
print("Missing dates:", df_clean["Date"].isna().sum())

print(df_clean["Date"].head())

Date data type: datetime64[ns]
Missing dates: 0
1   2021-01-01
2   2021-01-02
3   2021-01-03
4   2021-01-04
5   2021-01-05
Name: Date, dtype: datetime64[ns]

In [38]:
# Check numeric column data types
print(df_clean.dtypes)

# Check statistical ranges
display(
    df_clean[
        [
            "Conversion_Rate",
            "Acquisition_Cost",
            "ROI",
            "Clicks",
            "Impressions",
            "Engagement_Score"
        ]
    ].describe()
)

Campaign_ID                 object
Company                     object
Campaign_Type               object
Target_Audience             object
Duration                    object
Channel_Used               float64
Conversion_Rate             object
Acquisition_Cost           float64
ROI                        float64
Location                    object
Language                    object
Clicks                       int64
Impressions                  int64
Engagement_Score             int64
Customer_Segment            object
Date                datetime64[ns]
dtype: object

,Acquisition_Cost,ROI,Clicks,Impressions,Engagement_Score
count,0.0,200000.000000,200000.000000,200000.000000,200000.000000
mean,NaN,5.002438,549.772030,5507.301520,5.494710
std,NaN,1.734488,260.019056,2596.864286,2.872581
min,NaN,2.000000,100.000000,1000.000000,1.000000
25%,NaN,3.500000,325.000000,3266.000000,3.000000
50%,NaN,5.010000,550.000000,5517.500000,5.000000
75%,NaN,6.510000,775.000000,7753.000000,8.000000
max,NaN,8.000000,1000.000000,10000.000000,10.000000

In [39]:
df_clean["Conversion_Rate"] = pd.to_numeric(
    df_clean["Conversion_Rate"].astype(str).str.replace('"', '', regex=False).str.strip(),
    errors="coerce"
)

print("Conversion rates outside 0-1:",
      (~df_clean["Conversion_Rate"].between(0, 1)).sum())

print("Negative acquisition costs:",
      (df_clean["Acquisition_Cost"] < 0).sum())

print("Negative ROI values:",
      (df_clean["ROI"] < 0).sum())

print("Clicks greater than impressions:",
      (df_clean["Clicks"] > df_clean["Impressions"]).sum())

print("Invalid engagement scores:",
      (~df_clean["Engagement_Score"].between(1, 10)).sum())

print("\nDate range:")
print("Start:", df_clean["Date"].min())
print("End:", df_clean["Date"].max())

print("\nFinal shape:", df_clean.shape)
print("Missing values:", df_clean.isnull().sum().sum())
print("Duplicate rows:", df_clean.duplicated().sum())

Conversion rates outside 0-1: 200000
Negative acquisition costs: 0
Negative ROI values: 0
Clicks greater than impressions: 0
Invalid engagement scores: 0

Date range:
Start: 2021-01-01 00:00:00
End: 2021-12-31 00:00:00

Final shape: (200000, 16)
Missing values: 400000
Duplicate rows: 0

In [41]:
print("Export successful!")
print("Rows exported:", len(df_clean))
print("Columns exported:", len(df_clean.columns))

Export successful!
Rows exported: 200000
Columns exported: 16